version: "3.9"

services:
  forecast_api:
    build: .
    container_name: tutorial_forecast_as_service
    volumes:
      - .:/app/tutorial_forecast_as_service
      - ../helpers_root:/helpers_root
      - ../tutorial_prophet:/app/tutorial_prophet
    environment:
      # TODO(Alvino): To be replaced with dynamic sourcing via devops/docker_setenv.sh.
      - CSFY_HOST_NAME=dev1
      - PYTHONPATH=/app:/helpers_root
    ports:
      - "8000:8000"
