services:
  ollama-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    environment:
      - OLLAMA_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL=mistral:latest
    volumes:
      - .:/app
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:0.7.0
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama/models

volumes:
  ollama_models:
